### PR TITLE
+function to check repository using docker hub api

### PR DESCRIPTION
**Pull request by foxbg**
Replced regclient with a bash function (using curl and jq) 
TODO: check API rate limit to avoid error
replaced -s with -a
update check line is commented out (can be enabled)

### CODE REVIEW

**Comment by mag37** [comment]
Very nice ideas! I remember I tried to figure out something similar to not be depending on regctl.
I've not tried it yet and would like to do some extensive testing before merging.

Seems like you're considering other "hubs", are they all following the same standard naming and URLs?

Like `lscr.io` and `ghcr.io` ?

**Comment by foxbg** [comment]
Hi,
regctl is good package, but if it can be replaced with few lines of code it will simplify the script for the end user.

The hub option should work with other hubs if they support the same API.
Unfortunately on the host I tested all images images are from one hub.

It would b easy to test if I have a image from these repos... It is simple curl request. Do you have any examples?

**Comment by mag37** [comment]
Just did some testing on one machine. 
With all 22 containers fully updated, when I run this branch I get 8 with errors and 8 with (false) updates available.

Seems to get a bunch of parse errors during the registry lookups, this is the . . . -loading at the start:
```sh
. . . . parse error: Invalid numeric literal at line 1, column 4
. parse error: Invalid numeric literal at line 1, column 4
. . . . . . parse error: Invalid numeric literal at line 1, column 4
. parse error: Invalid numeric literal at line 1, column 4
. . . . parse error: Invalid numeric literal at line 1, column 4
. . . . . . . 
```

And this is the debug log of one container:
```sh
+ for i in $(docker ps $Stopped --filter "name=$SearchName" --format '{{.Names}}')
+ printf '. '
. ++ docker inspect audiobookshelf '--format={{.Config.Image}}'
+ RepoUrl=ghcr.io/advplyr/audiobookshelf:latest
++ docker image inspect ghcr.io/advplyr/audiobookshelf:latest --format '{{.RepoDigests}}'
++ cut -f 2 -d @
+ LocalHash='sha256:43d5c05a7c5d08b60192d9a21b7bd0a27f2f19c296718fea2a0a47075b779773]'
++ regcheck ghcr.io/advplyr/audiobookshelf:latest
++ hub=hub.docker.com
++ namespace=
++ repository=
++ arg=ghcr.io/advplyr/audiobookshelf:latest
++ [[ ghcr.io/advplyr/audiobookshelf:latest == *\:* ]]
+++ echo ghcr.io/advplyr/audiobookshelf:latest
+++ cut -f 2 -d :
++ tag=latest
+++ echo ghcr.io/advplyr/audiobookshelf:latest
+++ cut -f 1 -d :
++ arg=ghcr.io/advplyr/audiobookshelf
++ [[ ghcr.io/advplyr/audiobookshelf == *\.* ]]
+++ echo ghcr.io/advplyr/audiobookshelf
+++ cut -f 1 -d /
++ hub=ghcr.io
+++ echo ghcr.io/advplyr/audiobookshelf
+++ cut -f 2- -d /
++ arg=advplyr/audiobookshelf
++ [[ advplyr/audiobookshelf == *\/* ]]
+++ echo advplyr/audiobookshelf
+++ cut -f 1 -d /
++ namespace=advplyr
+++ echo advplyr/audiobookshelf
+++ cut -f 2 -d /
++ repository=audiobookshelf
+++ curl -L -s -w '%{http_code}' https://ghcr.io/v2/namespaces/advplyr/repositories/audiobookshelf/tags/latest
++ res='Not Found404'
++ http_code=404
++ '[' 12 -eq 3 ']'
++ body='Not Found'
++ echo Not Found
++ jq -r .digest
parse error: Invalid numeric literal at line 1, column 4
+ RegHash=
+ GotErrors+=("$i")
```

**Comment by mag37** [comment]
> It would b easy to test if I have a image from these repos... It is simple curl request. Do you have any examples?

These are some of the images in the above example:

lscr.io/linuxserver/syncthing
ghcr.io/dgtlmoon/changedetection.io
lscr.io/linuxserver/adguardhome-sync:latest
adguard/adguardhome
lscr.io/linuxserver/ddclient:latest
ghcr.io/advplyr/audiobookshelf:latest

**Comment by foxbg** [comment]
Quick search showed following
It does no look like lscr.io has an api and ghcr.io requires authentication (and it does not seem to use same docker hub API)
have to add error check in my code to avoid jq errors when http code is different from 200.

Assuming regctl is working correctly with listed packages there should be a way. 

Here is what I get when trying to access API:
```
 curl -i https://ghcr.io/v2/
HTTP/2 401
content-type: application/json
docker-distribution-api-version: registry/2.0
www-authenticate: Bearer realm="https://ghcr.io/token",service="ghcr.io",scope="repository:user/image:pull"
date: Fri, 17 Nov 2023 22:04:08 GMT
content-length: 73
x-github-request-id: 8F40:13C7:DE1A7:132ABB:6557E358

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required"}]}

```
and

```
curl -i https://lscr.io/v2/
HTTP/2 401
date: Fri, 17 Nov 2023 22:04:51 GMT
content-type: application/json
content-length: 73
docker-distribution-api-version: registry/2.0
www-authenticate: Bearer realm="https://ghcr.io/token",service="ghcr.io",scope="repository:user/image:pull"
x-github-request-id: 0F4E:18BD:44BF6E:4E6219:6557E383
strict-transport-security: max-age=15724800; includeSubDomains

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required"}]}

```

**Comment by foxbg** [comment]
Did not find applicable documentation :(
Here is what I found as possible solution
```
USER='linuxserver'
IMAGE='adguardhome-sync'
# for a public image you can get a fake NOOP token to use
TOKEN=`curl https://ghcr.io/token\?scope\="repository:$USER/$IMAGE:pull"|jq -r .token`
echo $TOKEN
#curl -H "Authorization: Bearer $TOKEN" https://ghcr.io/v2/$USER/$IMAGE/tags/list|jq
curl -H "Authorization: Bearer $TOKEN" https://ghcr.io/v2/$USER/$IMAGE/manifests/v0.3.1-ls16

```
Not sure if I have the correct digest here

**Comment by foxbg** [comment]
After additional testing it looks the code is not ready for prod. (di not think of case where image will have ot in the name).
When ime permits will work on improving.
Closing

**Pull request closed without merging**
