### PR TITLE
Added Matrix-Synapse notification Template

### PR DESCRIPTION
**Pull request by silverbios**
Similar to other templates like telegram, this script can send notification about avaliable Update Images to Synapse server.

### CODE REVIEW

**Comment by mag37** [comment]
Superb! Thank you for the contribution!

**Comment by hellblue** [comment]
how can i test if notification works for matrix from conole with notify.sh
i added my data in the file

**Comment by mag37** [comment]
> how can i test if notification works for matrix from conole with notify.sh i added my data in the file

You could either just test the curl string - manually set the variables you filled in the file and set something like `Test123` as the MsgBody
```
curl -sS -o /dev/null --fail -X PUT "$MatrixServer/_matrix/client/r0/rooms/$Room_id/send/m.room.message?access_token=$AccessToken" -H 'Content-Type: application/json' -d "$MsgBody"
```

Or you could do `source notify.sh; send_notification "Test123" `

**Comment by hellblue** [comment]
thank you i got it working now

**Pull request merged**
